services:

  ftp-server:
    # image: fauria/vsftpd
    # platform: linux/amd64
    # # ports:
    # #   - "21:21"
    # #   - "21100-21110:21100-21110"
    # # volumes:
    # #   - /Users/your_username/Documents/ftp:/home/vsftpd
    # environment:
    #   FTP_USER: ftptest
    #   FTP_PASS: ftptest
    #   PASV_ADDRESS: 127.0.0.1
    #   PASV_MIN_PORT: 21100
    #   PASV_MAX_PORT: 21110
    image: bfren/ftps
    platform: linux/amd64
    # ports:
    #   - "21:21"
    #   - "21100-21110:21100-21110"
    # volumes:
    #   - /Users/your_username/Documents/ftp:/home/vsftpd
    environment:
      BF_FTPS_VSFTPD_USER: ftptest
      BF_FTPS_VSFTPD_PASS: ftptest
      BF_FTPS_EXTERNAL_URI: ftp-server
    restart: unless-stopped

  fluentftp.memoryprofiling:
    image: ${DOCKER_REGISTRY-}fluentftpmemoryprofiling
    build:
      context: ../
      dockerfile: FluentFTP.MemoryProfiling/Dockerfile
    depends_on:
      - ftp-server
